spring:
  datasource:
    username: root
    url: jdbc:mysql://192.168.56.10:3316/shop?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    password: root
  application:
    name: democache
  redis:
    host: 192.168.56.10
    port: 6379
    database: 0    # 数据库索引
    timeout: 1800000 # 连接超时毫秒
    lettuce:
      pool:
        max-active: 20  # 连接池最大连接数
        max-wait: -1 # 最大阻塞等待时间 -1 表示没有限制
        max-idle: 5 # 连接池最大空闲连接数


server:
  port: 8081

