spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3316/account_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  application:
    name: account1
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880